[package]
name = "iftar"
version = "0.1.0"
authors = ["omerakgoz34 <omerakgoz34@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.3.1", features = ["https-native"] }
scraper = "0.12.0"
chrono = "0.4.19"

[profile.release.package."*"]
debug = false
opt-level = 3
codegen-units = 1

[profile.release]
debug = false
opt-level = 3
codegen-units = 1
lto = "fat"