# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "iftar"
version = "0.1.2"
authors = ["omerakgoz34 <omerakgoz34@gmail.com>"]
edition = "2021"

[dependencies]
minreq = { version = "^2.3", features = ["https"] }
scraper = "^0.12"
chrono = "^0.4"

[profile.release.package."*"]
debug = false
strip = true
opt-level = 3
incremental = false
codegen-units = 1

[profile.release]
debug = false
strip = true
opt-level = 3
incremental = false
codegen-units = 1
lto = true
panic = "abort"