name: "BUILD Release: macOS"

on:
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
            profile: default
            toolchain: stable-x86_64-apple-darwin
            override: true

    - name: Build
      run: cargo build --release

    - name: File Permission
      run: chmod +x ./target/release/iftar

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: iftar_macos
        path: target/release/iftar
