name: "BUILD Release: Linux"

on:
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
            profile: default
            toolchain: stable-x86_64-unknown-linux-gnu
            override: true

    - name: Build
      run: cargo build --release

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: iftar_linux
        path: target/release/iftar
