name: "BUILD Release: Linux"

on:
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
            profile: default
            toolchain: stable-x86_64-unknown-linux-gnu
            override: true

    - name: Install Linux Libraries
      run: sudo apt update && sudo apt install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Build
      run: cargo build --release

    - name: File Permission
      run: chmod +x ./target/release/iftar

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: iftar_linux
        path: target/release/iftar
