name: "BUILD: macOS"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Rust Version
      run: rustc -vV

    - name: Build
      run: cargo build

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: iftar_macos
        path: target/build/iftar
